In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
with open("/content/cricket.txt",'r',encoding='utf-8') as file:       # load the dataset
  cricket_history = file.read()                                       # read the dataset

In [ ]:
cricket_history               # display the dataset

'Cricket history is particularly murky and vague as to the exact origins of the game, it is believed to have been born in England in the late middle ages.\n\nEdward III banned a game similar to cricket in 1369, ‘pila baculorea’ or ‘club ball’ as it was known, as he saw it as being a distraction to his war effort.\n\nDerek Birley in his wonderful book, ‘A Social History of English Cricket’ suggests the game came to England with the French during the time of the Norman Invasion, that their word ‘criquet’ was the dialect name for a variation of club ball, the game Edward the III had sought to eradicate.\n\nThere is record of the word ‘creag’ as a derivative of the word creaget in 1299-1300 in the Royal Wardrobe Accounts, for the then Prince Edward the II to play ‘creag’ and other games.\n\nThere is no evidence that creag was the same as criquet, the links are too tenuous and games rarely appear in any records of this time unless the aristocracy were playing them or trying to have them era

In [ ]:
# filters = '!"#$%&()*+,-./:;<=>?@[]\\^_'{|}~\t'    # define the filters we want

In [ ]:
tokenizer =tf.keras.preprocessing.text.Tokenizer()                         # define the tokenizer

# tokenizer =tf.keras.preprocessing.text.Tokenizer(filters = filters)      # define the tokenizer with the filters

In [ ]:
tokenizer.fit_on_texts([cricket_history])         # convert the text into numerical values

In [ ]:
tokenizer.get_config()    # display the tokens given for the words and other details about the tokenizer

{'num_words': None,
 'filters': '!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
 'lower': True,
 'split': ' ',
 'char_level': False,
 'oov_token': None,
 'document_count': 1,
 'word_counts': '{"cricket": 35, "history": 2, "is": 8, "particularly": 2, "murky": 1, "and": 47, "vague": 1, "as": 25, "to": 45, "the": 148, "exact": 1, "origins": 1, "of": 48, "game": 22, "it": 22, "believed": 1, "have": 4, "been": 4, "born": 2, "in": 57, "england": 15, "late": 1, "middle": 1, "ages": 1, "edward": 3, "iii": 2, "banned": 1, "a": 22, "similar": 2, "1369": 1, "\\u2018pila": 1, "baculorea\\u2019": 1, "or": 5, "\\u2018club": 1, "ball\\u2019": 1, "was": 15, "known": 1, "he": 1, "saw": 7, "being": 8, "distraction": 1, "his": 2, "war": 1, "effort": 1, "derek": 1, "birley": 1, "wonderful": 1, "book": 1, "\\u2018a": 1, "social": 1, "english": 6, "cricket\\u2019": 3, "suggests": 1, "came": 1, "with": 16, "french": 1, "during": 2, "time": 5, "norman": 1, "invasion": 2, "that": 9, "their": 4, "word": 3, "\\u2018criq

In [ ]:
tokenizer.word_index   # display the indexes of words

{'the': 1,
 'in': 2,
 'of': 3,
 'and': 4,
 'to': 5,
 'cricket': 6,
 'as': 7,
 'game': 8,
 'it': 9,
 'a': 10,
 'for': 11,
 'with': 12,
 'were': 13,
 'england': 14,
 'was': 15,
 'its': 16,
 'played': 17,
 'by': 18,
 'that': 19,
 'had': 20,
 'at': 21,
 'is': 22,
 'being': 23,
 'games': 24,
 'saw': 25,
 'they': 26,
 'new': 27,
 'australia': 28,
 'english': 29,
 'playing': 30,
 'first': 31,
 'an': 32,
 'be': 33,
 'between': 34,
 'from': 35,
 'technology': 36,
 'or': 37,
 'time': 38,
 'this': 39,
 'aristocracy': 40,
 'recorded': 41,
 'century': 42,
 'two': 43,
 'on': 44,
 'after': 45,
 'bowling': 46,
 'twenty': 47,
 'have': 48,
 'been': 49,
 'their': 50,
 'club': 51,
 'them': 52,
 'classes': 53,
 'teams': 54,
 'up': 55,
 'match': 56,
 'players': 57,
 'into': 58,
 'began': 59,
 'spread': 60,
 'south': 61,
 'international': 62,
 'only': 63,
 'edward': 64,
 'cricket’': 65,
 'word': 66,
 'ball': 67,
 'there': 68,
 'play': 69,
 'men': 70,
 'way': 71,
 'seen': 72,
 'side': 73,
 'best': 74,
 'becom

In [ ]:
input_sequences = []
for sentence in cricket_history.split("\n"):                     # divide the dataset into sentences
  # print(sentence)                                              # print the divided sentences
  token_list = tokenizer.texts_to_sequences([sentence])[0]       # give tokens for the sentences
  # print(token_list)                                            # print the sentences with indexes
  for i in range(1, len(token_list)):                            # define the inputs of the Neural Network
    sequence = token_list[:i+1]
    input_sequences.append(sequence)

In [ ]:
input_sequences[:5]         # display the first 5 inputs (last index of each row shows the index of output word)

[[6, 93],
 [6, 93, 22],
 [6, 93, 22, 94],
 [6, 93, 22, 94, 178],
 [6, 93, 22, 94, 178, 4]]

In [ ]:
max_length = max([len(input_sequence) for input_sequence in input_sequences])    # find the maximum length of the sequences
max_length                                                                       # display the maximum length

55

In [ ]:
input_sequences = np.array(tf.keras.preprocessing.sequence.pad_sequences(input_sequences, maxlen=max_length, padding='pre'))      # convert all the sequences to maximum length by adding the padding (every sequence should have 55 indexes, for that we add 0's at the front of the sequence)

In [ ]:
input_sequences[:5]    # display the first 5 input sequences

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   6,  93],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          6,  93,  22],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,
         93,  22,  94],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,

In [ ]:
input_sequences[1]      # display only the first input sequence

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  6, 93, 22], dtype=int32)

In [ ]:
# split the input sequence into input part and output part
x = input_sequences[:, :-1]      # define all the indexes except the last index as input (x)
y = input_sequences[:, -1]       # define the last index as output/ label (y)

In [ ]:
x[0]   # display the 0 element of the x (first input)

# x[1]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 6], dtype=int32)

In [ ]:
y       # display the all y values (outputs/labels)

array([ 93,  22,  94, ...,  38, 177, 622], dtype=int32)

In [ ]:
tokenizer.word_index     # display all the words with indexes

In [ ]:
len(tokenizer.word_index)     # display the total no. of words

622

In [ ]:
num_classes = len(tokenizer.word_index) + 1     # define the no. of classes (add 1 to no. of words bcz indexes starts with 0)
num_classes                                     # display the no. of classes

623

In [ ]:
y = np.array(tf.keras.utils.to_categorical(y, num_classes=num_classes))  # one hot encoded the y values

In [ ]:
y[0]        # display the 0 element of the y (in here if index value is 93, only the (93+1) position have the 1 as value, all other positions have 0)

# y[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [ ]:
# create the model
model = tf.keras.models.Sequential()                                                # use sequential API
model.add(tf.keras.layers.Embedding(num_classes, 80, input_length=max_length-1))    # add an embedding layer (create input values to 80 values) (input values as 622)
model.add(tf.keras.layers.LSTM(100))                                                # add a LSTM layer with 100 units
model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))                 # define the output layer with 623 neurons and softmax activation function (bcz this is a multi class classification problem)

In [ ]:
model.summary()        # display summary of the model

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 54, 80)            49840     
                                                                 
 lstm (LSTM)                 (None, 100)               72400     
                                                                 
 dense (Dense)               (None, 623)               62923     
                                                                 
Total params: 185163 (723.29 KB)
Trainable params: 185163 (723.29 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
# compile the model
model.compile(loss='categorical_crossentropy',     # use categorical cross entropy as loss function
              optimizer='adam',                    # use adam optimizer
              metrics=['accuracy'])                # use accuracy to measure the model

In [ ]:
# train the model
history = model.fit(x, y, epochs=100)          # train the model with 100 epochs by giving x (inputs) and y (outputs) values

Epoch 1/100
47/47 [==============================] - 5s 43ms/step - loss: 6.1300 - accuracy: 0.0816
Epoch 2/100
47/47 [==============================] - 2s 44ms/step - loss: 5.6359 - accuracy: 0.0911
Epoch 3/100
47/47 [==============================] - 2s 43ms/step - loss: 5.5567 - accuracy: 0.0911
Epoch 4/100
47/47 [==============================] - 2s 43ms/step - loss: 5.5060 - accuracy: 0.0911
Epoch 5/100
47/47 [==============================] - 3s 59ms/step - loss: 5.4340 - accuracy: 0.0911
Epoch 6/100
47/47 [==============================] - 3s 57ms/step - loss: 5.3543 - accuracy: 0.0911
Epoch 7/100
47/47 [==============================] - 2s 43ms/step - loss: 5.2644 - accuracy: 0.1005
Epoch 8/100
47/47 [==============================] - 2s 43ms/step - loss: 5.1589 - accuracy: 0.1221
Epoch 9/100
47/47 [==============================] - 2s 43ms/step - loss: 5.0436 - accuracy: 0.1255
Epoch 10/100
47/47 [==============================] - 2s 43ms/step - loss: 4.9274 - accuracy: 0.1350

# **Predict using model**

In [ ]:
input_text = 'cricket begin'   # define the 'cricket begin' as the input

In [ ]:
token_list = tokenizer.texts_to_sequences([input_text])[0]   # convert the input into numerical values
print(token_list)                                            # print the numerical values

[6, 408]


In [ ]:
token_list = tf.keras.preprocessing.sequence.pad_sequences([token_list], maxlen=max_length-1, padding='pre')    # convert all the sequences to maximum length by adding the padding (every sequence should have 55 indexes, for that we add 0's at the front of the sequence)
print(token_list)                                                                                               # print the coverted sequence

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   6 408]]


In [ ]:
predicted = np.argmax(model.predict(token_list), axis=-1)    # predict the next word (label) by giving the token_list as input (use argmax bcz we have multi classes)
print(predicted)                                             # print the token of output word

1/1 [==============================] - 0s 477ms/step
[1]


In [ ]:
for word, index in tokenizer.word_index.items():      # get the word of the given index
  if index == predicted:                              # when token index equals to predicted index we get the word
    print(word)                                       # print the word

the


In [ ]:
input_text = "cricket begin"   # predict a whole sentence by repeating this process
for i in range(6):             # predict 6 words
  token_list = tokenizer.texts_to_sequences([input_text])[0]
  token_list = tf.keras.preprocessing.sequence.pad_sequences([token_list], maxlen=max_length-1, padding='pre')
  predicted = np.argmax(model.predict(token_list), axis=-1)
  output_word = ""
  for word, index in tokenizer.word_index.items():
    if index == predicted:
      output_word = word
      break
  input_text += " " + output_word

print(input_text)

1/1 [==============================] - 0s 29ms/step
cricket begin the west indies and india by
